from treemendous.domain import MutationResult

class PackedMutationResults:
    @property
    def changed_offsets(self) -> memoryview: ...
    @property
    def changed_spans(self) -> memoryview: ...
    @property
    def changed_lengths(self) -> memoryview: ...
    @property
    def fully_covered(self) -> memoryview: ...
    def materialize(self) -> tuple[MutationResult, ...]: ...
    def __len__(self) -> int: ...

class ExactBatchManager:
    def __init__(
        self, domain: list[tuple[int, int]], initially_available: bool
    ) -> None: ...
    def mutate_packed(self, operations: object) -> PackedMutationResults: ...
    def snapshot_data(self) -> tuple[tuple[tuple[int, int], ...], int]: ...
