from treemendous.domain import MutationResult

class BatchLimitError(ValueError): ...

class PackedMutationResults:
    @property
    def changed_offsets(self) -> memoryview: ...
    @property
    def changed_spans(self) -> memoryview: ...
    @property
    def changed_lengths(self) -> memoryview: ...
    @property
    def fully_covered(self) -> memoryview: ...
    def materialize(self) -> tuple[MutationResult, ...]: ...
    def __len__(self) -> int: ...

class ExactBatchManager:
    def __init__(
        self,
        domain: list[tuple[int, int]],
        initially_available: bool,
        max_operations: int,
        max_live_intervals: int,
        max_changed_spans: int,
        max_result_bytes: int,
        max_work_units: int,
    ) -> None: ...
    def mutate_packed(self, operations: bytes) -> PackedMutationResults: ...
    def mutate_materialized(self, operations: bytes) -> tuple[MutationResult, ...]: ...
    def snapshot_data(self) -> tuple[tuple[tuple[int, int], ...], int]: ...
    def _set_failpoint(self, name: str, occurrence: int = 0) -> None: ...
    def _clear_failpoint(self) -> None: ...
